defmodule Bylaw.Contract.HeadPropertiesAcceptanceTest do
  use ExUnit.Case

  import Bylaw.Contract.ContractHelper

  alias Bylaw.Contract
  alias Bylaw.Contract.Fixtures.Generated
  alias Bylaw.Contract.Fixtures.Table
  alias Bylaw.Contract.Fixtures.Greeter
  alias Bylaw.Contract.Fixtures.Plain

  test "reports a function clause that no test selected" do
    report =
      Contract.observe([Greeter], fn ->
        Greeter.greet(:admin)
        Greeter.greet(:member)
      end)

    assert missed(report, Greeter, :clause) == [{:greet, 1, 3}]
  end

  test "reports nothing about clauses when every clause was selected" do
    report =
      Contract.observe([Greeter], fn ->
        Greeter.greet(:admin)
        Greeter.greet(:member)
        Greeter.greet({:guest, 1})
      end)

    assert missed(report, Greeter, :clause) == []
  end

  test "counts how many calls each clause selected" do
    report =
      Contract.observe([Greeter], fn ->
        for _call <- 1..3, do: Greeter.greet(:admin)
        Greeter.greet({:guest, 1})
      end)

    assert property(report, Greeter, :clause, {:greet, 1, 1}).count == 3
    assert property(report, Greeter, :clause, {:greet, 1, 2}).count == 0
    assert property(report, Greeter, :clause, {:greet, 1, 3}).count == 1
  end

  test "has no clause properties for single clause private or compiler generated functions" do
    report =
      Contract.observe([Plain], fn ->
        Plain.single(1)
        Plain.with_default(1)
      end)

    assert Enum.filter(report.properties, &(&1.module == Plain)) == []
  end

  test "has no clause properties and only unassessable spec properties for functions generated by macros" do
    report =
      Contract.observe([Generated], fn ->
        Generated.one(:a)
        Generated.two(:b)
      end)

    properties = Enum.filter(report.properties, &(&1.module == Generated))

    refute Enum.any?(properties, &(&1.kind == :clause))
    assert Enum.all?(properties, &(&1.status == :unassessable))
    assert Enum.any?(properties, &(&1.reason =~ "generated"))
  end

  test "has no clause or guard properties for clauses a comprehension generates from one source line" do
    report = Contract.observe([Table], fn -> Table.classify("1.2.3.4") end)

    properties = Enum.filter(report.properties, &(&1.module == Table))

    refute Enum.any?(properties, &(&1.kind in [:clause, :guard_rejection]))
  end
end
