defmodule Bylaw.Ecto.Query.Checks.NamedBindingsTest do
  use ExUnit.Case, async: true

  import Ecto.Query

  alias Bylaw.Ecto.Query.Checks.NamedBindings
  alias Bylaw.Ecto.Query.Issue
  alias Ecto.Repo.Queryable

  @prepare_query_operations [:all, :update_all, :delete_all, :stream, :insert_all]

  defmodule Post do
    use Ecto.Schema

    schema "posts" do
      field(:organisation_id, :integer)
      field(:title, :string)

      has_many(:comments, Bylaw.Ecto.Query.Checks.NamedBindingsTest.Comment)
    end
  end

  defmodule Comment do
    use Ecto.Schema

    schema "comments" do
      field(:organisation_id, :integer)
      field(:body, :string)

      belongs_to(:post, Bylaw.Ecto.Query.Checks.NamedBindingsTest.Post)
    end
  end

  defmodule CaptureRepo do
    @spec prepare_query(atom(), term(), keyword()) :: no_return()
    def prepare_query(operation, query, opts) do
      # Stop before adapter execution; the check only needs the query shape
      # handed to prepare_query/3 by Ecto's repo lookup path.
      send(self(), {:captured_prepare_query, operation, query, opts})
      raise "captured query"
    end
  end

  describe "validate/3" do
    test "passes when root expressions use named binding references" do
      query =
        from(post in Post,
          as: :post,
          where: as(:post).organisation_id == ^123,
          select: as(:post).id
        )

      assert :ok = NamedBindings.validate(:all, query, [])
    end

    test "passes when root expressions use named binding list references" do
      query =
        Post
        |> from(as: :post)
        |> where([post: post], post.organisation_id == ^123)
        |> select([post: post], post.id)

      assert :ok = NamedBindings.validate(:all, query, [])
    end

    test "passes for every Ecto prepare_query operation when aliases are used" do
      query =
        from(post in Post,
          as: :post,
          where: post.organisation_id == ^123
        )

      Enum.each(@prepare_query_operations, fn operation ->
        assert :ok = NamedBindings.validate(operation, query, [])
      end)
    end

    test "requires a named root binding" do
      query = from(post in Post, where: post.organisation_id == ^123)

      assert {:error, issues} = NamedBindings.validate(:all, query, [])

      assert_reasons(issues, [:missing_root_as, :positional_binding_reference])
      assert Enum.any?(issues, &(Map.get(&1.meta, :binding) == :root))
    end

    test "does not count a join alias as the root alias" do
      query =
        from(post in Post,
          join: comment in Comment,
          as: :comment,
          on: true
        )

      assert {:error, %Issue{} = issue} = NamedBindings.validate(:all, query, [])
      assert issue.check == NamedBindings
      assert issue.meta.reason == :missing_root_as
      assert issue.meta.binding == :root
    end

    test "requires every join to declare an alias" do
      query =
        from(post in Post,
          as: :post,
          join: comment in Comment,
          on: as(:comment).post_id == as(:post).id
        )

      assert {:error, %Issue{} = issue} = NamedBindings.validate(:all, query, [])
      assert issue.meta.reason == :missing_join_as
      assert issue.meta.join_index == 0
      assert issue.meta.binding_index == 1
      assert issue.message == "expected Ecto query join binding to declare an :as alias"
    end

    test "returns issues for every join that omits an alias" do
      query =
        from(post in Post,
          as: :post,
          join: comment in Comment,
          on: true,
          left_join: second_comment in Comment,
          on: true
        )

      assert {:error, issues} = NamedBindings.validate(:all, query, [])

      assert_reasons(issues, [:missing_join_as, :missing_join_as])
      assert Enum.map(issues, & &1.meta.join_index) == [0, 1]
      assert Enum.map(issues, & &1.meta.binding_index) == [1, 2]
    end

    test "allows local root field references when the root binding has an alias" do
      query =
        from(post in Post,
          as: :post,
          where: post.organisation_id == ^123
        )

      assert :ok = NamedBindings.validate(:all, query, [])
    end

    test "allows keyword field shortcuts when the root binding has an alias" do
      query = from(Post, as: :post, where: [organisation_id: ^123])

      assert :ok = NamedBindings.validate(:all, query, [])
    end

    test "requires a named root binding for caller-authored keyword field shortcuts" do
      query = from(Post, where: [organisation_id: ^123])

      assert {:error, issues} = NamedBindings.validate(:all, query, [])

      assert_reasons(issues, [:missing_root_as, :positional_binding_reference])
    end

    test "ignores rootless keyword predicates generated by Ecto repo lookups" do
      {operation, query, _opts} =
        capture_prepare_query(fn ->
          Queryable.get_by(
            CaptureRepo,
            Post,
            [id: 1, organisation_id: 123],
            repo_tuplet()
          )
        end)

      assert operation == :all
      assert :ok = NamedBindings.validate(operation, query, [])
    end

    test "still validates caller-authored subqueries under Ecto repo lookups" do
      inner_query =
        from(post in Post,
          where: post.organisation_id == ^123
        )

      {operation, query, _opts} =
        capture_prepare_query(fn ->
          Queryable.get_by(
            CaptureRepo,
            from(post in subquery(inner_query)),
            [id: 1],
            repo_tuplet()
          )
        end)

      assert operation == :all
      assert {:error, issues} = NamedBindings.validate(operation, query, [])
      assert_reasons(issues, [:missing_root_as, :positional_binding_reference])
    end

    test "allows field expressions when the referenced binding has an alias" do
      field = :organisation_id

      query =
        from(post in Post,
          as: :post,
          where: field(post, ^field) == ^123
        )

      assert :ok = NamedBindings.validate(:all, query, [])
    end

    test "passes joins when aliases are declared and predicates use named references" do
      query =
        from(post in Post,
          as: :post,
          join: comment in Comment,
          as: :comment,
          on: as(:comment).post_id == as(:post).id,
          where: as(:post).organisation_id == ^123
        )

      assert :ok = NamedBindings.validate(:all, query, [])
    end

    test "passes joins when aliases are declared and predicates use named binding lists" do
      query =
        Post
        |> from(as: :post)
        |> join(:inner, [post: post], comment in Comment,
          as: :comment,
          on: comment.post_id == post.id
        )
        |> where(
          [post: post, comment: comment],
          comment.organisation_id == post.organisation_id
        )

      assert :ok = NamedBindings.validate(:all, query, [])
    end

    test "allows local field references in join predicates when bindings are aliased" do
      query =
        from(post in Post,
          as: :post,
          join: comment in Comment,
          as: :comment,
          on: comment.post_id == post.id
        )

      assert :ok = NamedBindings.validate(:all, query, [])
    end

    test "reports field references that target unaliased join bindings" do
      query =
        from(post in Post,
          as: :post,
          join: comment in Comment,
          on: comment.post_id == post.id
        )

      assert {:error, issues} = NamedBindings.validate(:all, query, [])

      assert_reasons(issues, [
        :missing_join_as,
        :positional_binding_reference
      ])

      positional_issue = List.last(issues)

      assert positional_issue.meta.macro == :join_on
      assert positional_issue.meta.binding_index == 1
      assert positional_issue.meta.binding_alias == nil
      assert positional_issue.meta.field == :post_id

      assert positional_issue.message ==
               "expected Ecto query join_on field reference on binding 1 to target a binding with an :as alias"
    end

    test "allows association join sources because Ecto stores them as association metadata" do
      query =
        from(post in Post,
          as: :post,
          join: comment in assoc(post, :comments),
          as: :comment,
          on: true
        )

      assert :ok = NamedBindings.validate(:all, query, [])
    end

    test "allows joined preloads because Ecto stores them as association indexes" do
      query =
        from(post in Post,
          as: :post,
          join: comment in assoc(post, :comments),
          as: :comment,
          on: true,
          preload: [comments: comment]
        )

      assert :ok = NamedBindings.validate(:all, query, [])
    end

    test "allows field references in ordering, grouping, distinct, windows, and updates when bindings are aliased" do
      query =
        from(post in Post,
          as: :post,
          order_by: post.title,
          group_by: post.organisation_id,
          distinct: post.id,
          windows: [by_organisation: [partition_by: post.organisation_id]],
          update: [set: [title: post.title]]
        )

      assert :ok = NamedBindings.validate(:update_all, query, [])
    end

    test "allows aliased local field references in nested subqueries" do
      query =
        from(post in Post,
          as: :post,
          where:
            exists(
              from(comment in Comment,
                as: :comment,
                where: comment.post_id == parent_as(:post).id
              )
            )
        )

      assert :ok = NamedBindings.validate(:all, query, [])
    end

    test "validates nested subqueries that omit binding aliases" do
      query =
        from(post in Post,
          as: :post,
          where:
            exists(
              from(comment in Comment,
                where: comment.post_id == parent_as(:post).id
              )
            )
        )

      assert {:error, issues} = NamedBindings.validate(:all, query, [])

      assert_reasons(issues, [:missing_root_as, :positional_binding_reference])

      issue = List.last(issues)
      assert issue.meta.reason == :positional_binding_reference
      assert issue.meta.binding_alias == nil
      assert issue.meta.field == :post_id
    end

    test "accepts parent_as references in nested subqueries" do
      query =
        from(post in Post,
          as: :post,
          where:
            exists(
              from(comment in Comment,
                as: :comment,
                where: as(:comment).post_id == parent_as(:post).id
              )
            )
        )

      assert :ok = NamedBindings.validate(:all, query, [])
    end

    test "does not reject whole-binding selects because Ecto has no as(:name) equivalent" do
      query = from(post in Post, as: :post, select: post)

      assert :ok = NamedBindings.validate(:all, query, [])
    end

    test "respects the explicit query-level escape hatch" do
      query = from(post in Post, where: post.organisation_id == ^123)

      assert :ok = NamedBindings.validate(:all, query, named_bindings: [validate: false])
    end

    test "validates when validate is explicitly true" do
      query = from(post in Post, where: post.organisation_id == ^123)

      assert {:error, [%Issue{} | _issues]} =
               NamedBindings.validate(:all, query, named_bindings: [validate: true])
    end

    test "requires an explicit false escape hatch" do
      query = from(post in Post, where: post.organisation_id == ^123)

      assert {:error, [%Issue{} | _issues]} =
               NamedBindings.validate(:all, query, named_bindings: [validate: nil])
    end

    test "raises when top-level opts are not a keyword list" do
      query = from(post in Post)

      assert_raise ArgumentError, "expected opts to be a keyword list, got: :invalid", fn ->
        NamedBindings.validate(:all, query, :invalid)
      end
    end

    test "raises when top-level opts are a non-keyword list" do
      query = from(post in Post)

      assert_raise ArgumentError, "expected opts to be a keyword list, got: [:invalid]", fn ->
        NamedBindings.validate(:all, query, [:invalid])
      end
    end

    test "raises when check opts are not a keyword list" do
      query = from(post in Post)

      assert_raise ArgumentError,
                   "expected :named_bindings opts to be a keyword list, got: :invalid",
                   fn ->
                     NamedBindings.validate(:all, query, named_bindings: :invalid)
                   end
    end

    test "raises when check opts are a non-keyword list" do
      query = from(post in Post)

      assert_raise ArgumentError,
                   "expected :named_bindings opts to be a keyword list, got: [:invalid]",
                   fn ->
                     NamedBindings.validate(:all, query, named_bindings: [:invalid])
                   end
    end

    test "raises for unknown check options" do
      query = from(post in Post)

      assert_raise ArgumentError, "unknown :named_bindings option: :unknown", fn ->
        NamedBindings.validate(:all, query, named_bindings: [unknown: true])
      end
    end
  end

  defp assert_reasons(issues, reasons) do
    issues = List.wrap(issues)
    assert Enum.map(issues, & &1.meta.reason) == reasons
  end

  defp capture_prepare_query(fun) do
    assert_raise RuntimeError, "captured query", fun
    assert_receive {:captured_prepare_query, operation, query, opts}
    {operation, query, opts}
  end

  defp repo_tuplet do
    {%{adapter: __MODULE__.CaptureAdapter, cache: nil, repo: CaptureRepo}, []}
  end
end
