defmodule Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour do
  @moduledoc false

  @callback run(term()) :: term()
  @callback guarded(term()) :: term()
  @callback with_default(term(), term()) :: term()
end

defmodule Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.SecondaryBehaviour do
  @moduledoc false

  @callback list(term()) :: list(term())
end

defmodule Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.UnconfiguredBehaviour do
  @moduledoc false

  @callback call(term()) :: term()
end

defmodule Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest do
  use Credo.Test.Case

  alias Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctions

  @primary_behaviour __MODULE__.PrimaryBehaviour
  @secondary_behaviour __MODULE__.SecondaryBehaviour

  test "does not report when only callback functions are public" do
    """
    defmodule Example do
      @behaviour Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour

      @impl Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour
      def run(value), do: value
    end
    """
    |> to_source_file()
    |> run_check(NoExtraPublicBehaviourFunctions, behaviours: [@primary_behaviour])
    |> refute_issues()
  end

  test "reports an extra public function" do
    """
    defmodule Example do
      @behaviour Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour

      @impl Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour
      def run(value), do: value

      def helper(value), do: value
    end
    """
    |> to_source_file()
    |> run_check(NoExtraPublicBehaviourFunctions, behaviours: [@primary_behaviour])
    |> assert_issue(%{
      line_no: 7,
      trigger: "helper/1",
      message: ~r/Public function `helper\/1` is not a callback/
    })
  end

  test "reports an extra delegated public function" do
    """
    defmodule Example do
      @behaviour Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour

      @impl Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour
      def run(value), do: value

      defdelegate helper(value), to: Helpers
    end
    """
    |> to_source_file()
    |> run_check(NoExtraPublicBehaviourFunctions, behaviours: [@primary_behaviour])
    |> assert_issue(%{
      line_no: 7,
      trigger: "helper/1",
      message: ~r/Public function `helper\/1` is not a callback/
    })
  end

  test "reports public arities generated by default arguments in delegated functions" do
    """
    defmodule Example do
      @behaviour Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour

      @impl Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour
      defdelegate with_default(value, opts \\\\ []), to: Helpers
    end
    """
    |> to_source_file()
    |> run_check(NoExtraPublicBehaviourFunctions, behaviours: [@primary_behaviour])
    |> assert_issue(%{
      line_no: 5,
      trigger: "with_default/1"
    })
  end

  test "does not report private helper functions" do
    """
    defmodule Example do
      @behaviour Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour

      @impl Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour
      def run(value), do: helper(value)

      defp helper(value), do: value
    end
    """
    |> to_source_file()
    |> run_check(NoExtraPublicBehaviourFunctions, behaviours: [@primary_behaviour])
    |> refute_issues()
  end

  test "does not report explicitly allowed extra public functions" do
    """
    defmodule Example do
      @behaviour Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour

      @impl Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour
      def run(value), do: value

      def child_spec(opts), do: opts
    end
    """
    |> to_source_file()
    |> run_check(NoExtraPublicBehaviourFunctions,
      behaviours: [@primary_behaviour],
      allowed: [child_spec: 1]
    )
    |> refute_issues()
  end

  test "supports multiple behaviours by unioning callbacks" do
    """
    defmodule Example do
      @behaviour Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour
      @behaviour Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.SecondaryBehaviour

      @impl Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour
      def run(value), do: value

      @impl Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.SecondaryBehaviour
      def list(value), do: [value]
    end
    """
    |> to_source_file()
    |> run_check(NoExtraPublicBehaviourFunctions,
      behaviours: [@primary_behaviour, @secondary_behaviour]
    )
    |> refute_issues()
  end

  test "ignores behaviours not listed in config" do
    """
    defmodule Example do
      @behaviour Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.UnconfiguredBehaviour

      @impl Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.UnconfiguredBehaviour
      def call(value), do: value

      def helper(value), do: value
    end
    """
    |> to_source_file()
    |> run_check(NoExtraPublicBehaviourFunctions, behaviours: [@primary_behaviour])
    |> refute_issues()
  end

  test "does not check every behaviour when behaviours config is empty" do
    """
    defmodule Example do
      @behaviour Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour

      @impl Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour
      def run(value), do: value

      def helper(value), do: value
    end
    """
    |> to_source_file()
    |> run_check(NoExtraPublicBehaviourFunctions)
    |> refute_issues()
  end

  test "does not crash when a configured behaviour cannot be loaded" do
    """
    defmodule Example do
      @behaviour MissingBehaviourForNoExtraPublicBehaviourFunctions

      def helper(value), do: value
    end
    """
    |> to_source_file()
    |> run_check(NoExtraPublicBehaviourFunctions,
      behaviours: [MissingBehaviourForNoExtraPublicBehaviourFunctions]
    )
    |> refute_issues()
  end

  test "does not report public macros" do
    """
    defmodule Example do
      @behaviour Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour

      @impl Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour
      def run(value), do: value

      defmacro helper(value), do: value
    end
    """
    |> to_source_file()
    |> run_check(NoExtraPublicBehaviourFunctions, behaviours: [@primary_behaviour])
    |> refute_issues()
  end

  test "respects excluded_paths" do
    """
    defmodule Example do
      @behaviour Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour

      @impl Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour
      def run(value), do: value

      def helper(value), do: value
    end
    """
    |> to_source_file("lib/example.ex")
    |> run_check(NoExtraPublicBehaviourFunctions,
      behaviours: [@primary_behaviour],
      excluded_paths: ["lib/example.ex"]
    )
    |> refute_issues()
  end

  test "supports aliased behaviour attributes" do
    """
    defmodule Example do
      alias Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour

      @behaviour PrimaryBehaviour

      @impl PrimaryBehaviour
      def run(value), do: value

      def helper(value), do: value
    end
    """
    |> to_source_file()
    |> run_check(NoExtraPublicBehaviourFunctions, behaviours: [@primary_behaviour])
    |> assert_issue(%{
      line_no: 9,
      trigger: "helper/1"
    })
  end

  test "reports one issue for each extra public signature with multiple clauses" do
    issues =
      """
      defmodule Example do
        @behaviour Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour

        @impl Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour
        def run(value), do: value

        def helper(nil), do: nil
        def helper(value), do: value
      end
      """
      |> to_source_file()
      |> run_check(NoExtraPublicBehaviourFunctions, behaviours: [@primary_behaviour])

    assert [%Credo.Issue{trigger: "helper/1"}] = issues
  end

  test "handles guarded callback function heads" do
    """
    defmodule Example do
      @behaviour Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour

      @impl Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour
      def guarded(value) when is_binary(value), do: value
    end
    """
    |> to_source_file()
    |> run_check(NoExtraPublicBehaviourFunctions, behaviours: [@primary_behaviour])
    |> refute_issues()
  end

  test "reports public arities generated by default arguments when they are not callbacks" do
    """
    defmodule Example do
      @behaviour Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour

      @impl Bylaw.Credo.Check.Elixir.NoExtraPublicBehaviourFunctionsTest.PrimaryBehaviour
      def with_default(value, opts \\\\ []), do: {value, opts}
    end
    """
    |> to_source_file()
    |> run_check(NoExtraPublicBehaviourFunctions, behaviours: [@primary_behaviour])
    |> assert_issue(%{
      line_no: 5,
      trigger: "with_default/1"
    })
  end
end
